### ISSUE TITLE
Only 443 port can be used？

### ISSUE THREAD

**Issue by qqfbleach** [mindcollapse/SoftEtherPy#1]
i use 5555 port to connect, it failes.(i can use vpn server manage to log in from this port) 

shows:
in get_http_response
    with self.socket.makefile('rb') as socket_file:
AttributeError: **exit**

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
I think this issue has something to do with the method `with` having the need for an `__exit__` method. With will try to store the `__exit__`method and since there is nothing in api.py in the `connect()` method to satisfy that it throws the AttributeError. But I'm not sure and I'm reproducing the same problem here.

After messing around wih this API a bit, I decided to see if the error wasn't anything that important. When I run the command again it says the socket is already connected.

**Comment by volodymyrsmirnov** [comment]
Hi gents, can you tell me which exact version of SoftEther VPN are you using. I will try to reproduce the bug and find a solution. In our environment everything seems to work ok, but we are using previous version of VPN server (Ver 4.12, Build 9514, Intel x64 / AMD64) for Linux so I assume that could be a core of a problem.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Hey, I'm currently using Ver 4.15 Build 9546 Intel/Amd64. I'll install your version tomorrow morning to see if it works. They could have changed the payload a bit between versions.
https://www.softether.org/5-download/history

**Comment by volodymyrsmirnov** [comment]
Ok, so the reason is more than trivial. I've never tested this lib on Python 2.7 because in our projects we use 3.x branch. On 2.7 it shows an error and on 3.4 everything is fine with the latest 4.15 build installed on the server. 

![image](https://cloud.githubusercontent.com/assets/1248015/7226147/8d37784c-e74e-11e4-8042-6bb5cddb4a2a.png)

I'll fix the bug and update this issue to notify you, guys.

**Comment by volodymyrsmirnov** [comment]
The problem been fixed with d9aad75 and I was able to connect to the server using Python 2.7 and obtain the information. This also works well with 5555 port. 

Please test and let me know if it works for you,

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Everything is working great, thank you so much! It works for python 2.7 and
python 3. I have another question if you have time. I'm trying to create
custom methods in the API, specifically UserPasswordSet. How did you find
where the methods were abstracted and what fields they require?

def set_user_password(self, hub_name=None, name=None, password=None):

```
    payload = {
```

> ```
>         'HubName': ('string', [hub_name]),
> 
>         'Name': ('string', [name]),
> 
>         'Password': ('string', [password]),
> 
> 
> 
>     }
> 
> 
> 
>     return self.call_method('UserPasswordSet', payload)
> ```

Thanks for your time

**Comment by volodymyrsmirnov** [comment]
@MumbleFysh you can get the full list here
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Admin.c#L443

I assume they are constantly adding new RPC methods and change existing ones, but that's not something I'm planning to support.

DECLARE_RPC and DECLARE_RPC_EX macros are responsible for defining the API methods.

For example:
`DECLARE_RPC_EX("Test", RPC_TEST, StTest, InRpcTest, OutRpcTest, FreeRpcTest)`

Look at InRpcTest and OutRpcTest voids in the same file. First one defines the input format (see PackGet calls) and second one specifies what is returned (see PackAdd calls). 

```
void InRpcTest(RPC_TEST *t, PACK *p)
{
    Zero(t, sizeof(RPC_TEST));
    t->IntValue = PackGetInt(p, "IntValue");
    t->Int64Value = PackGetInt64(p, "Int64Value");
    PackGetStr(p, "StrValue", t->StrValue, sizeof(t->StrValue));
    PackGetUniStr(p, "UniStrValue", t->UniStrValue, sizeof(t->UniStrValue));
}

void OutRpcTest(PACK *p, RPC_TEST *t)
{
    PackAddInt(p, "IntValue", t->IntValue);
    PackAddInt64(p, "Int64Value", t->Int64Value);
    PackAddStr(p, "StrValue", t->StrValue);
    PackAddUniStr(p, "UniStrValue", t->UniStrValue);
}
```

**Comment by qqfbleach** [comment]
Thank you very much.It works. Great job！
