### ISSUE TITLE
Add documentation about how to setup the CGI endpoint for the API client

### ISSUE THREAD

**Issue by luke-gru** [mindcollapse/SoftEtherPy#2]
Hi, I've been reading the SoftEther documentation and I can't find anywhere where it says how to setup the VPN Server Management endpoints on the server that has SoftEther VPN installed. 

In the file`api.py` in your project, I see the endpoint path is `/vpsnsvc/connect.cgi`, and I see this is also defined in a file in the source code of SoftEther itself, so is there a way to get this API client communicating with SoftEther VPN without having to write my own CGI scripts? It seems like this functionality must be provided by SoftEther, but I'm having a lot of trouble finding more information about this.

Any help would be greatly appreciated.

Thanks,

**Comment by volodymyrsmirnov** [comment]
Hi luke-gru,

All those HTTP requests in the beginning of connection are made for only 1 purpose - mask VPN connection and pass restrictive firewalls.

Endpoint path is hardcoded in C sources of VPN server.

If I understand your question right, there is no way how you can communicate with SoftEther using HTTP API because there is no HTTP API at all. After the connection is established, all further operations are made using their own proprietary communication and serialization protocol, so you have to write a middleware using this library.

Let me know if that is what you asked for ;)

**Comment by luke-gru** [comment]
Hi,

Thanks for the prompt response. Yes, I was asking about a HTTP API, and I found out shortly after asking you that there is no API. So I just created a small php script that shells out to the 'vpncmd' tool and that's good enough for my needs :)

Thanks again for the help.
